### ISSUE TITLE
Issues with playing around the demo site

### ISSUE THREAD

**Issue by necinc** [cloudflare/binjs-demo#2]
Very promising proposal!

I was curious to see how different BinaryAST bundle would be from a regular js file.
I've downloaded and set up the latest Firefox Nightly to encode binast format, but couldn't see the difference.

So I've decided to copy requests from the network panel as cURL requests and download those files to my machine. I've downloaded two files, one with binast flags on and another with those flags off. And even after all that being done I haven't got any difference.

Here is the line in [the article](https://blog.cloudflare.com/binary-ast/#how-do-i-test-binaryast-on-my-website) which made me think that there should be some difference in files content:
>Now, when opening a website with either of the Workers installed, Firefox will get BinaryAST instead of JavaScript automatically.

![Screen Shot 2019-06-01 at 3 34 27 PM](https://user-images.githubusercontent.com/8607893/58748594-da538680-8483-11e9-89b8-1c5a5d935f41.png)

Am I doing something wrong? Is there some way to compare both versions? Or I just misunderstood how all these binjs stuff work?

**Comment by xtuc** [comment]
> Am I doing something wrong? Is there some way to compare both versions? Or I just misunderstood how all these binjs stuff work?

You are right, the demo is currently not working due to another experimentation I did on my zone.

Closing since it's a duplicate; see https://github.com/cloudflare/binast-cf-worker/issues/1

**Comment by xtuc** [comment]
This should be fixed now.

**Comment by necinc** [comment]
Yes, it really is.
Awesome work!
Thanks!
